<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    protected $except = [
        'api/*',
        '/api/test',
        '/api/reset-password',
        '/api/job-titles',
        '/api/companies',
        '/api/industries',
        '/api/skills',
        '/api/country',
        '/api/state',
        '/api/city',
        '/api/industry',
        '/api/company',
        '/api/job_title',
        '/api/sponsorships',
        '/api/send_attendee_list_by_email',
        '/api/resource',
        '/api/resource/*',
        '/api/updateprofile',
        '/api/checkingAuthenticated',
        '/api/changepassword',
        'api/forgot-password',
        '/api/login',
        '/api/register',
        '/api/logout',
        '/api/events',
        '/api/events/*',
        '/api/attendeed/upload/*',
        '/api/attendees',
        '/api/attendees/*',
        '/api/feedbacks',
        '/api/feedbacks/*',
        '/api/sponsors',
        '/api/sponsors/*',
        '/api/eventsponsors/*',
        '/api/send-mail-to-attendee/*',
        '/api/send-sms-to-attendee/*',
        '/api/message',
        '/api/send-email',
        '/api/totalattendeesOrganizer',
        '/api/totalevents',
        '/api/upcomingevents',
        '/api/totalsponsors',
        '/api/totalattendees/*',
        '/api/totalsponsors/*',
        '/api/totalattendeetype/*',
        '/api/attendeeProfileCompleted/*',
        '/api/notifications-list',
        '/api/notifications',
        '/api/reports',
        '/api/event-report',
        '/api/event-report-download/*',
        '/api/reports/*',
        '/api/send-reminder-on-start-date',
        '/api/send-reminder-one-hour-before-start-time',
        '/api/emailnotifications',
        '/api/send-mail-reminder-regular-interval',
        '/api/send-sms-reminder-regular-interval',
        '/api/send-sms', 
        '/api/logout'
    ];
}
